### ISSUE TITLE
Sort Scrolling up Jumpiness

### ISSUE THREAD

**Issue by LucisFeris** [jadus/jquery-sortScroll#1]
Hi, thanks for this excellent plugin! I seem to be having an issue, when scrolling down the div stays in the exact same spot and the animation is smooth, but when scrolling up the div moves up a few pixels and then jumps back down into place when the scrolling is done.

I've read some posts that stated this might be related to not explicitly declaring div heights...any idea as to why this would be happening?

Thanks.

**Comment by jadus** [comment]
Can you provide a jsfiddle or codepen showing the bug ? Try to simplify you html and css and see what exactly causes the glitch.

**Comment by LucisFeris** [comment]
Thanks for your reply, it seems to be doing it in both directions in the simplified version.  Here is the jsfiddle:

https://jsfiddle.net/yn4x5g0k/3/

**Comment by jadus** [comment]
add this to your fiddle :
`body, h4
{
  margin:0
}`

**Comment by LucisFeris** [comment]
Thank you! Works like a charm :+1:
